import NavBar from '@/components/shared/NavBar'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Hero from '@/components/HeroPage'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar />
      <Hero />
        {children}
        <div>Footer</div>
        </body>
    </html>
  )
}
